### ISSUE TITLE
Possibly highlight entire color?

### ISSUE THREAD

**Issue by radicaled** [naumovs/vscode-ext-color-highlight#3]
Right now the plugin only creates a colored bordered around the color in question -- is it possible for there an option to change the background (and foreground, if necessary) of the color string? Something like pigments: https://atom.io/packages/pigments ?

It may just be a combination of my font / theme / syntax, but it's hard to read the text surrounded by the border and would be less obtrusive if it just highlighted the entire block of text.

**Comment by naumovs** [comment]
nice. I'll try to update my plugin

**Comment by axefrog** [comment]
I'd like to see this too. It's easier to get a sense of a colour palette when you can see a solid block of colour, as opposed to a border. Naturally you'd want to make sure you choose an appropriate foreground colour too, though it's easy enough to find an algorithm to do this.

http://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color

**Comment by gluons** [comment]
#5 fulfill this issue. Now, we are happy. 😄
