### ISSUE TITLE
Disable highlighting of "word" colours?

### ISSUE THREAD

**Issue by girvo** [naumovs/vscode-ext-color-highlight#4]
Hey there, lovely extension

I'd love to be able to disable the highlighting of colour "words": `grey`, `green`, etc. while still highlighting the hex-codes in Javascript. This is because in React Native, we set variables for each colour hex-code that often overlap with the "CSS" definition of a colour word!

**Comment by naumovs** [comment]
Update the plugin and set "color-highlight.matchWords" option to your preference
